projectName: VinBigData

Property:
    input_sizes: [512, 640, 768, 896, 1024, 1280, 1280, 1536, 1536]
    test_size: 512

    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    colors: [
        (39, 129, 113), (164, 80, 133), (83, 122, 114), (99, 81, 172), 
        (95, 56, 104), (37, 84, 86), (14, 89, 122), (80, 7, 65), 
        (10, 102, 25), (90, 185, 109), (106, 110, 132), (169, 158, 85), (188, 185, 26)
        ]
    anchor_ratios: [(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]
    anchor_scales: [2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]
    classes: [
            'Aortic_enlargement', 'Atelectasis', 'Calcification',
            'Cardiomegaly', 'Consolidation', 'ILD', 'Infiltration', 'Lung_Opacity',
            'Nodule/Mass', 'Other_lesion', 'Pleural_effusion', 'Pleural_thickening',
            'Pneumothorax', 'Pulmonary_fibrosis'
            ]

Training:

Inference:
    threshold: 0.2
    iou_threshold: 0.2
